from tkinter import *
from tkinter import messagebox
from tkinter import filedialog
from PIL import ImageTk, Image 
import mysql.connector
root=Tk()
login = Toplevel(root)
login.withdraw()
register = Toplevel(root)
register.withdraw()
name = StringVar()
paswrd = StringVar()
user_name = StringVar()
email = StringVar()
user_password = StringVar()
fisrt_n = StringVar()
second_n = StringVar()    
country = StringVar()      
province = StringVar()
city = StringVar()
zip_code = StringVar()
gender = StringVar()
contact = StringVar()
dob = StringVar()
mydb = mysql.connector.connect(host='localhost',user='root',password='12345678')
mycursor = mydb.cursor()
mydb.connect(database='ProjectDB')
def insert_user(un,pd,e,f,s,co,pr,ci,zc,g,uc,dob):
    mycursor.execute("INSERT INTO Registration(Email,Username,Rpassword) values (%s,%s,%s)" ,(e,un,pd)) 
    mydb.commit()
    mycursor.execute("SELECT RId FROM Registration WHERE Email=%s",(e,))
    rid = mycursor.fetchone()
    mycursor.execute("INSERT INTO Users(RId,fName,lName,Country,Province,City,Zipcode,Gender,UContact,DOB) values (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)",(rid[0],f,s,co,pr,ci,zc,g,uc,dob))
    mydb.commit()
def login_user(n,p):
    mycursor.execute("SELECT * FROM Registration WHERE Username=%s and RPassword=%s",(n,p))
    verify=mycursor.fetchone()
    if verify is not None :
        return True
    else:
        return False
def register_user(n):
    mycursor.execute("SELECT * FROM Registration WHERE Username=%s",(n,))
    verify=mycursor.fetchone()
    if verify is not None :
        return True
    else:
        return False

def main_gui(): 
    root.withdraw()
    login.update()
    login.deiconify()
    login.lift()
    login.geometry("300x230")
    login.title("Pet Store Login")
    image_animals = ImageTk.PhotoImage(Image.open("D:\ProjectDB\pet2.png"))
    Animal_frame=LabelFrame(login,bd=3)
    Animal_frame.place(x=0,y=0,width=300,height=230)
    animal_1=Label(Animal_frame,image=image_animals)
    animal_1.grid(row=0,column=0,padx=50,pady=40)
    Label(login,text = "Name").grid(row = 1, column = 0)
    Entry(login, textvariable=name).grid(row = 1, column = 1)  
    Label(login,text = "Password").grid(row = 2, column = 0)  
    Entry(login,textvariable = paswrd, show="*").grid(row = 2, column = 1)  
    Button(login, text = "Login",command = buttonpressed).grid(row = 4, column = 0)  
    Button(login, text = "Register",command = registeration).grid(row = 5, column = 0) 
    login.mainloop()
def registeration():
    login.withdraw()
    register.update()
    register.deiconify()
    register.lift()
    register.title("Pet Store Register")
    register.geometry("600x290")
    image_animals = ImageTk.PhotoImage(Image.open("D:\ProjectDB\pet2.png"))
    Animal_frame=LabelFrame(register,bg="Light cyan")
    Animal_frame.place(x=290,y=0,width=300,height=230)
    animal_1=Label(Animal_frame,image=image_animals,bg='Light cyan')
    animal_1.grid(row=0,column=0,padx=50,pady=40)
    Label(register,text = "Email").grid(row = 0, column = 0)
    Entry(register, textvariable=email).grid(row = 0, column = 1)
    Label(register,text = "UserName").grid(row = 1, column = 0)
    Entry(register, textvariable=user_name).grid(row = 1, column = 1)  
    Label(register,text = "Password").grid(row = 2, column = 0)  
    Entry(register, textvariable=user_password).grid(row = 2, column = 1)  
    Label(register,text = "First Name").grid(row = 3, column = 0)
    Entry(register, textvariable=fisrt_n).grid(row = 3, column = 1)  
    Label(register,text = "Last Name").grid(row = 4, column = 0)  
    Entry(register, textvariable=second_n).grid(row = 4, column = 1)  
    Label(register,text = "Country").grid(row = 5, column = 0)
    Entry(register, textvariable=country).grid(row = 5, column = 1)  
    Label(register,text = "Province").grid(row = 6, column = 0)  
    Entry(register, textvariable=province).grid(row = 6, column = 1)  
    Label(register,text = "City").grid(row = 7, column = 0)  
    Entry(register, textvariable=city).grid(row = 7, column = 1) 
    Label(register,text = "Zip Code").grid(row = 8, column = 0)  
    Entry(register, textvariable=zip_code).grid(row = 8, column = 1) 
    Label(register,text = "Gender").grid(row = 9, column = 0)  
    Entry(register, textvariable=gender).grid(row = 9, column = 1) 
    Label(register,text = "Contact").grid(row = 10, column = 0)  
    Entry(register, textvariable=contact).grid(row = 10, column = 1) 
    Label(register,text = "DOB(format YYYY-MM-DD)").grid(row = 11, column = 0)  
    Entry(register, textvariable=dob).grid(row = 11, column = 1) 
    Button(register, text = "Submit",command = add_user).grid(row = 12, column = 0)  
    register.mainloop()
def add_user():
    if len(user_name.get()) !=0 and len(user_password.get())!=0  and len(email.get()) !=0 and len(fisrt_n.get())!=0 and len(second_n.get()) !=0 and len(country.get())!=0 and len(province.get()) !=0 and len(city.get())!=0 and len(zip_code.get()) !=0 and len(gender.get())!=0 and len(dob.get()) !=0:
        check = register_user(user_name.get())
        if check is False:
            insert_user(user_name.get(),user_password.get(),len(email.get()),len(fisrt_n.get()),len(second_n.get()),len(country.get()),len(province.get()),len(city.get()),len(zip_code.get()),len(gender.get()),len(contact.get()),len(dob.get()))
            register.destroy()
            login.update()
            login.deiconify()
            login.lift()
        else:
            messagebox.showerror("Add User Error", "Username Exists")
    else:
        Label(register,text = "Some fields are empty.",font="TimeNewRomans 18 italic",fg="Green",bg="light yellow").grid(row = 11, column = 3,padx=15)    
def buttonpressed():
    if login_user(name.get(),paswrd.get()):
        login.destroy()
        final_gui()
    else:
        Label(login,text="Try again...!!!").place(x=60,y=50)

def final_gui(): 
    root.update()
    root.deiconify()
    root.lift()
    root.title("PetStore")
    root.geometry("1360x1000")
    Heading=LabelFrame(root,bd=2,relief="groove",bg="light yellow")
    Heading.place(x=0,y=0,width=1380,height=55)
    image_logo=ImageTk.PhotoImage(Image.open("D:\ProjectDB\Logo.png"))
    label_logo=Label(Heading,image=image_logo)
    label_logo.grid(row=0,column=0)
    Label(Heading,text="Pet Store",font="arial 20 bold italic",bg="light yellow",fg="Dark Red").grid(row=0,column=1)
    Label(Heading,text="Shopping is now more easier!!!",font="TimeNewRomans 18 italic",fg="Green",bg="light yellow").grid(row=0,column=2,padx=80)
    mycursor.execute("SELECT fname,lname from users u, registration r where u.rid=r.rid and r.username=%s",(name.get(),))
    uName = mycursor.fetchone()
    p_pic = ImageTk.PhotoImage(Image.open("D:\ProjectDB\plogo.png"))
    Label(Heading,image=p_pic).place(x=1060)
    Label(Heading,text="Hello,"+str(uName[0])+" "+str(uName[1]),font="TimeNewRomans 18 italic",fg="Green",bg="light yellow").place(x=1110,y=10)
    Products_frame=LabelFrame(root,bd=2,relief="groove",text="Products",font="arial 18 bold",fg="dark blue")
    Products_frame.place(x=310,y=60,width=1040,height=620)
    Button_frame=LabelFrame(root,bd=2,relief="groove",bg='Light blue')
    Button_frame.place(x=2,y=60,width=300,height=380)
    def HideAllFrames():
        for widget in Products_frame.winfo_children():
            widget.destroy()
    def near_you():

        HideAllFrames()
        Label(Products_frame,text="Pets Near You",font="times 22 bold italic underline",fg="red").grid(row=0,column=0,padx=20)
        mycursor.execute("SELECT city from users u, registration r where u.rid=r.rid and r.username=%s",(name.get(),))
        city = mycursor.fetchone()
        mycursor.execute("SELECT * FROM Product p, users u  WHERE p.uid=u.uid and u.city = %s",(city[0],))
        pets = mycursor.fetchall()
        if len(pets)==0:
            Label(Products_frame,text="Sorry no pet to show.",font="arial 20 bold italic",bg="light yellow",fg="Dark Red").grid(row=1,column=0,padx=250)
            root.mainloop()
        count = 0
        current_pet = pets[count]
        p_name = current_pet[3]
        p_image = current_pet[4]
        p_desc = current_pet[5]
        p_weight = current_pet[6]
        p_price = current_pet[7]
        pet_frame=LabelFrame(Products_frame,bd=2,relief="groove")
        pet_frame.place(x=5,y=35,width=410,height=540)
        pet_image =ImageTk.PhotoImage(Image.open(p_image))
        Label(pet_frame,image=pet_image,bd=2).grid(row=0,column=0)
        pet_name1 = Label(Products_frame,text="Name:",font="times 16 bold",fg="Blue",bd=2)
        pet_name1.place(x=450,y=50)
        pet_name = Label(Products_frame,text=p_name,font="times 16",fg="Orange",bd=2)
        pet_name.place(x=550,y=80)
        pet_name1 = Label(Products_frame,text="Color:",font="times 16 bold",fg="Blue",bd=2)
        pet_name1.place(x=450,y=110)
        pet_name = Label(Products_frame,text=p_desc,font="times 16",fg="Orange",bd=2)
        pet_name.place(x=550,y=140)
        pet_name1 = Label(Products_frame,text="Weight:",font="times 16 bold",fg="Blue",bd=2)
        pet_name1.place(x=450,y=170)
        pet_name = Label(Products_frame,text=p_weight,font="times 16",fg="Orange",bd=2)
        pet_name.place(x=550,y=200)
        pet_name1 = Label(Products_frame,text="Price:",font="times 16 bold",fg="Blue",bd=2)
        pet_name1.place(x=450,y=230)
        pet_name = Label(Products_frame,text="Rs."+str(p_price),font="times 16",fg="Orange",bd=2)
        pet_name.place(x=550,y=260)
        mycursor.execute("SELECT UContact,City FROM Users WHERE UID = %s",(current_pet[2],))
        user_info = mycursor.fetchone()
        pet_name1 = Label(Products_frame,text="Location:",font="times 16 bold",fg="Blue",bd=2)
        pet_name1.place(x=450,y=290)
        pet_name = Label(Products_frame,text=user_info[1],font="times 16",fg="Orange",bd=2)
        pet_name.place(x=550,y=320)
        pet_name1 = Label(Products_frame,text="Want to buy!!!\nContact with the seller",font="times 22 bold",fg="White",bg="Green",bd=2)
        pet_name1.place(x=730,y=230)
        pet_name = Label(Products_frame,text="Phone No:"+ str(user_info[0]),font="times 16 bold",fg="Black",bd=2)
        pet_name.place(x=730,y=310)
        
        
        def next_pet(count,pets):
            HideAllFrames()
            count += 1
            count = count%len(pets)
            current_pet = pets[count]
            p_name = current_pet[3]
            p_image = current_pet[4]
            p_desc = current_pet[5]
            p_weight = current_pet[6]
            p_price = current_pet[7]
            Label(Products_frame,text="Pets Near You",font="times 22 bold italic underline",fg="red").grid(row=0,column=0,padx=20)
            pet_frame=LabelFrame(Products_frame,bd=2,relief="groove")
            pet_frame.place(x=5,y=35,width=410,height=540)
            pet_image =ImageTk.PhotoImage(Image.open(p_image))
            Label(pet_frame,image=pet_image,bd=2).grid(row=0,column=0)
            pet_name1 = Label(Products_frame,text="Name:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=50)
            pet_name = Label(Products_frame,text=p_name,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=80)
            pet_name1 = Label(Products_frame,text="Color:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=110)
            pet_name = Label(Products_frame,text=p_desc,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=140)
            pet_name1 = Label(Products_frame,text="Weight:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=170)
            pet_name = Label(Products_frame,text=p_weight,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=200)
            pet_name1 = Label(Products_frame,text="Price:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=230)
            pet_name = Label(Products_frame,text="Rs."+str(p_price),font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=260)
            mycursor.execute("SELECT UContact,City FROM Users WHERE UID = %s",(current_pet[2],))
            user_info = mycursor.fetchone()
            pet_name1 = Label(Products_frame,text="Location:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=290)
            pet_name = Label(Products_frame,text=user_info[1],font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=320)
            pet_name1 = Label(Products_frame,text="Want to buy!!!\nContact with the seller",font="times 22 bold",fg="White",bg="Green",bd=2)
            pet_name1.place(x=730,y=230)
            pet_name = Label(Products_frame,text="Phone No:"+ str(user_info[0]),font="times 16 bold",fg="Black",bd=2)
            pet_name.place(x=730,y=310)
            next_button = Button(Products_frame,text="Next",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:next_pet(count,pets)).place(x=730,y=500)
            prev_button = Button(Products_frame,text="Previous",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:prev_pet(count,pets)).place(x=430,y=500)
            root.mainloop()
        def prev_pet(count,pets):
            HideAllFrames()
            count -= 1
            count = count%len(pets)
            current_pet = pets[count]
            p_name = current_pet[3]
            p_image = current_pet[4]
            p_desc = current_pet[5]
            p_weight = current_pet[6]
            p_price = current_pet[7]
            Label(Products_frame,text="Pets Near You",font="times 22 bold italic underline",fg="red").grid(row=0,column=0,padx=20)
            pet_frame=LabelFrame(Products_frame,bd=2,relief="groove")
            pet_frame.place(x=5,y=35,width=410,height=540)
            pet_image =ImageTk.PhotoImage(Image.open(p_image))
            Label(pet_frame,image=pet_image,bd=2).grid(row=0,column=0)
            pet_name1 = Label(Products_frame,text="Name:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=50)
            pet_name = Label(Products_frame,text=p_name,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=80)
            pet_name1 = Label(Products_frame,text="Color:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=110)
            pet_name = Label(Products_frame,text=p_desc,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=140)
            pet_name1 = Label(Products_frame,text="Weight:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=170)
            pet_name = Label(Products_frame,text=p_weight,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=200)
            pet_name1 = Label(Products_frame,text="Price:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=230)
            pet_name = Label(Products_frame,text="Rs."+str(p_price),font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=260)
            mycursor.execute("SELECT UContact,City FROM Users WHERE UID = %s",(current_pet[2],))
            user_info = mycursor.fetchone()
            pet_name1 = Label(Products_frame,text="Location:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=290)
            pet_name = Label(Products_frame,text=user_info[1],font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=320)
            pet_name1 = Label(Products_frame,text="Want to buy!!!\nContact with the seller",font="times 22 bold",fg="White",bg="Green",bd=2)
            pet_name1.place(x=730,y=230)
            pet_name = Label(Products_frame,text="Phone No:"+ str(user_info[0]),font="times 16 bold",fg="Black",bd=2)
            pet_name.place(x=730,y=310)
            next_button = Button(Products_frame,text="Next",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:next_pet(count,pets)).place(x=730,y=500)
            prev_button = Button(Products_frame,text="Previous",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:prev_pet(count,pets)).place(x=430,y=500)
            root.mainloop()
        next_button = Button(Products_frame,text="Next",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:next_pet(count,pets)).place(x=730,y=500)
        prev_button = Button(Products_frame,text="Previous",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:prev_pet(count,pets)).place(x=430,y=500)
        root.mainloop()

    def button1():
        HideAllFrames()
        
        bird_label=Label(Products_frame,text="Birds",font="times 22 bold italic underline",fg="red").grid(row=0,column=0,padx=20)
        mycursor.execute("SELECT * FROM Product WHERE CId = %s",(3,))
        pets = mycursor.fetchall()
        
        count = 0
        current_pet = pets[count]
        p_name = current_pet[3]
        p_image = current_pet[4]
        p_desc = current_pet[5]
        p_weight = current_pet[6]
        p_price = current_pet[7]
        pet_frame=LabelFrame(Products_frame,bd=2,relief="groove")
        pet_frame.place(x=5,y=35,width=410,height=540)
        pet_image =ImageTk.PhotoImage(Image.open(p_image))
        Label(pet_frame,image=pet_image,bd=2).grid(row=0,column=0)
        pet_name1 = Label(Products_frame,text="Name:",font="times 16 bold",fg="Blue",bd=2)
        pet_name1.place(x=450,y=50)
        pet_name = Label(Products_frame,text=p_name,font="times 16",fg="Orange",bd=2)
        pet_name.place(x=550,y=80)
        pet_name1 = Label(Products_frame,text="Color:",font="times 16 bold",fg="Blue",bd=2)
        pet_name1.place(x=450,y=110)
        pet_name = Label(Products_frame,text=p_desc,font="times 16",fg="Orange",bd=2)
        pet_name.place(x=550,y=140)
        pet_name1 = Label(Products_frame,text="Weight:",font="times 16 bold",fg="Blue",bd=2)
        pet_name1.place(x=450,y=170)
        pet_name = Label(Products_frame,text=p_weight,font="times 16",fg="Orange",bd=2)
        pet_name.place(x=550,y=200)
        pet_name1 = Label(Products_frame,text="Price:",font="times 16 bold",fg="Blue",bd=2)
        pet_name1.place(x=450,y=230)
        pet_name = Label(Products_frame,text="Rs."+str(p_price),font="times 16",fg="Orange",bd=2)
        pet_name.place(x=550,y=260)
        mycursor.execute("SELECT UContact,City FROM Users WHERE UID = %s",(current_pet[2],))
        user_info = mycursor.fetchone()
        pet_name1 = Label(Products_frame,text="Location:",font="times 16 bold",fg="Blue",bd=2)
        pet_name1.place(x=450,y=290)
        pet_name = Label(Products_frame,text=user_info[1],font="times 16",fg="Orange",bd=2)
        pet_name.place(x=550,y=320)
        pet_name1 = Label(Products_frame,text="Want to buy!!!\nContact with the seller",font="times 22 bold",fg="White",bg="Green",bd=2)
        pet_name1.place(x=730,y=230)
        pet_name = Label(Products_frame,text="Phone No:"+ str(user_info[0]),font="times 16 bold",fg="Black",bd=2)
        pet_name.place(x=730,y=310)
        
        
        def next_pet(count,pets):
            HideAllFrames()
            count += 1
            count = count%len(pets)
            current_pet = pets[count]
            p_name = current_pet[3]
            p_image = current_pet[4]
            p_desc = current_pet[5]
            p_weight = current_pet[6]
            p_price = current_pet[7]
            bird_label=Label(Products_frame,text="Birds",font="times 22 bold italic underline",fg="red").grid(row=0,column=0,padx=20)
            pet_frame=LabelFrame(Products_frame,bd=2,relief="groove")
            pet_frame.place(x=5,y=35,width=410,height=540)
            pet_image =ImageTk.PhotoImage(Image.open(p_image))
            Label(pet_frame,image=pet_image,bd=2).grid(row=0,column=0)
            pet_name1 = Label(Products_frame,text="Name:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=50)
            pet_name = Label(Products_frame,text=p_name,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=80)
            pet_name1 = Label(Products_frame,text="Color:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=110)
            pet_name = Label(Products_frame,text=p_desc,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=140)
            pet_name1 = Label(Products_frame,text="Weight:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=170)
            pet_name = Label(Products_frame,text=p_weight,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=200)
            pet_name1 = Label(Products_frame,text="Price:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=230)
            pet_name = Label(Products_frame,text="Rs."+str(p_price),font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=260)
            mycursor.execute("SELECT UContact,City FROM Users WHERE UID = %s",(current_pet[2],))
            user_info = mycursor.fetchone()
            pet_name1 = Label(Products_frame,text="Location:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=290)
            pet_name = Label(Products_frame,text=user_info[1],font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=320)
            pet_name1 = Label(Products_frame,text="Want to buy!!!\nContact with the seller",font="times 22 bold",fg="White",bg="Green",bd=2)
            pet_name1.place(x=730,y=230)
            pet_name = Label(Products_frame,text="Phone No:"+ str(user_info[0]),font="times 16 bold",fg="Black",bd=2)
            pet_name.place(x=730,y=310)
            next_button = Button(Products_frame,text="Next",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:next_pet(count,pets)).place(x=730,y=500)
            prev_button = Button(Products_frame,text="Previous",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:prev_pet(count,pets)).place(x=430,y=500)
            root.mainloop()
        def prev_pet(count,pets):
            HideAllFrames()
            count -= 1
            count = count%len(pets)
            current_pet = pets[count]
            p_name = current_pet[3]
            p_image = current_pet[4]
            p_desc = current_pet[5]
            p_weight = current_pet[6]
            p_price = current_pet[7]
            bird_label=Label(Products_frame,text="Birds",font="times 22 bold italic underline",fg="red").grid(row=0,column=0,padx=20)
            pet_frame=LabelFrame(Products_frame,bd=2,relief="groove")
            pet_frame.place(x=5,y=35,width=410,height=540)
            pet_image =ImageTk.PhotoImage(Image.open(p_image))
            Label(pet_frame,image=pet_image,bd=2).grid(row=0,column=0)
            pet_name1 = Label(Products_frame,text="Name:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=50)
            pet_name = Label(Products_frame,text=p_name,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=80)
            pet_name1 = Label(Products_frame,text="Color:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=110)
            pet_name = Label(Products_frame,text=p_desc,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=140)
            pet_name1 = Label(Products_frame,text="Weight:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=170)
            pet_name = Label(Products_frame,text=p_weight,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=200)
            pet_name1 = Label(Products_frame,text="Price:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=230)
            pet_name = Label(Products_frame,text="Rs."+str(p_price),font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=260)
            mycursor.execute("SELECT UContact,City FROM Users WHERE UID = %s",(current_pet[2],))
            user_info = mycursor.fetchone()
            pet_name1 = Label(Products_frame,text="Location:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=290)
            pet_name = Label(Products_frame,text=user_info[1],font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=320)
            pet_name1 = Label(Products_frame,text="Want to buy!!!\nContact with the seller",font="times 22 bold",fg="White",bg="Green",bd=2)
            pet_name1.place(x=730,y=230)
            pet_name = Label(Products_frame,text="Phone No:"+ str(user_info[0]),font="times 16 bold",fg="Black",bd=2)
            pet_name.place(x=730,y=310)
            next_button = Button(Products_frame,text="Next",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:next_pet(count,pets)).place(x=730,y=500)
            prev_button = Button(Products_frame,text="Previous",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:prev_pet(count,pets)).place(x=430,y=500)
            root.mainloop()
        next_button = Button(Products_frame,text="Next",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:next_pet(count,pets)).place(x=730,y=500)
        prev_button = Button(Products_frame,text="Previous",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:prev_pet(count,pets)).place(x=430,y=500)
        root.mainloop()
    def button2():
        HideAllFrames()
        
        bird_label=Label(Products_frame,text="Cats",font="times 22 bold italic underline",fg="red").grid(row=0,column=0,padx=20)
        mycursor.execute("SELECT * FROM Product WHERE CId = %s",(1,))
        pets = mycursor.fetchall()
        count = 0
        current_pet = pets[count]
        p_name = current_pet[3]
        p_image = current_pet[4]
        p_desc = current_pet[5]
        p_weight = current_pet[6]
        p_price = current_pet[7]
        pet_frame=LabelFrame(Products_frame,bd=2,relief="groove")
        pet_frame.place(x=5,y=35,width=410,height=540)
        pet_image =ImageTk.PhotoImage(Image.open(p_image))
        Label(pet_frame,image=pet_image,bd=2).grid(row=0,column=0)
        pet_name1 = Label(Products_frame,text="Name:",font="times 16 bold",fg="Blue",bd=2)
        pet_name1.place(x=450,y=50)
        pet_name = Label(Products_frame,text=p_name,font="times 16",fg="Orange",bd=2)
        pet_name.place(x=550,y=80)
        pet_name1 = Label(Products_frame,text="Color:",font="times 16 bold",fg="Blue",bd=2)
        pet_name1.place(x=450,y=110)
        pet_name = Label(Products_frame,text=p_desc,font="times 16",fg="Orange",bd=2)
        pet_name.place(x=550,y=140)
        pet_name1 = Label(Products_frame,text="Weight:",font="times 16 bold",fg="Blue",bd=2)
        pet_name1.place(x=450,y=170)
        pet_name = Label(Products_frame,text=p_weight,font="times 16",fg="Orange",bd=2)
        pet_name.place(x=550,y=200)
        pet_name1 = Label(Products_frame,text="Price:",font="times 16 bold",fg="Blue",bd=2)
        pet_name1.place(x=450,y=230)
        pet_name = Label(Products_frame,text="Rs."+str(p_price),font="times 16",fg="Orange",bd=2)
        pet_name.place(x=550,y=260)
        mycursor.execute("SELECT UContact,City FROM Users WHERE UID = %s",(current_pet[2],))
        user_info = mycursor.fetchone()
        pet_name1 = Label(Products_frame,text="Location:",font="times 16 bold",fg="Blue",bd=2)
        pet_name1.place(x=450,y=290)
        pet_name = Label(Products_frame,text=user_info[1],font="times 16",fg="Orange",bd=2)
        pet_name.place(x=550,y=320)
        pet_name1 = Label(Products_frame,text="Want to buy!!!\nContact with the seller",font="times 22 bold",fg="White",bg="Green",bd=2)
        pet_name1.place(x=730,y=230)
        pet_name = Label(Products_frame,text="Phone No:"+ str(user_info[0]),font="times 16 bold",fg="Black",bd=2)
        pet_name.place(x=730,y=310)
        def next_pet(count,pets):
            HideAllFrames()
            count += 1
            count = count%len(pets)
            current_pet = pets[count]
            p_name = current_pet[3]
            p_image = current_pet[4]
            p_desc = current_pet[5]
            p_weight = current_pet[6]
            p_price = current_pet[7]
            bird_label=Label(Products_frame,text="Cats",font="times 22 bold italic underline",fg="red").grid(row=0,column=0,padx=20)
            pet_frame=LabelFrame(Products_frame,bd=2,relief="groove")
            pet_frame.place(x=5,y=35,width=410,height=540)
            pet_image =ImageTk.PhotoImage(Image.open(p_image))
            Label(pet_frame,image=pet_image,bd=2).grid(row=0,column=0)
            pet_name1 = Label(Products_frame,text="Name:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=50)
            pet_name = Label(Products_frame,text=p_name,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=80)
            pet_name1 = Label(Products_frame,text="Color:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=110)
            pet_name = Label(Products_frame,text=p_desc,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=140)
            pet_name1 = Label(Products_frame,text="Weight:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=170)
            pet_name = Label(Products_frame,text=p_weight,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=200)
            pet_name1 = Label(Products_frame,text="Price:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=230)
            pet_name = Label(Products_frame,text="Rs."+str(p_price),font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=260)
            mycursor.execute("SELECT UContact,City FROM Users WHERE UID = %s",(current_pet[2],))
            user_info = mycursor.fetchone()
            pet_name1 = Label(Products_frame,text="Location:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=290)
            pet_name = Label(Products_frame,text=user_info[1],font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=320)
            pet_name1 = Label(Products_frame,text="Want to buy!!!\nContact with the seller",font="times 22 bold",fg="White",bg="Green",bd=2)
            pet_name1.place(x=730,y=230)
            pet_name = Label(Products_frame,text="Phone No:"+ str(user_info[0]),font="times 16 bold",fg="Black",bd=2)
            pet_name.place(x=730,y=310)
            next_button = Button(Products_frame,text="Next",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:next_pet(count,pets)).place(x=730,y=500)
            prev_button = Button(Products_frame,text="Previous",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:prev_pet(count,pets)).place(x=430,y=500)
            root.mainloop()
        def prev_pet(count,pets):
            HideAllFrames()
            count -= 1
            count = count%len(pets)
            current_pet = pets[count]
            p_name = current_pet[3]
            p_image = current_pet[4]
            p_desc = current_pet[5]
            p_weight = current_pet[6]
            p_price = current_pet[7]
            bird_label=Label(Products_frame,text="Cats",font="times 22 bold italic underline",fg="red").grid(row=0,column=0,padx=20)
            pet_frame=LabelFrame(Products_frame,bd=2,relief="groove")
            pet_frame.place(x=5,y=35,width=410,height=540)
            pet_image =ImageTk.PhotoImage(Image.open(p_image))
            Label(pet_frame,image=pet_image,bd=2).grid(row=0,column=0)
            pet_name1 = Label(Products_frame,text="Name:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=50)
            pet_name = Label(Products_frame,text=p_name,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=80)
            pet_name1 = Label(Products_frame,text="Color:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=110)
            pet_name = Label(Products_frame,text=p_desc,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=140)
            pet_name1 = Label(Products_frame,text="Weight:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=170)
            pet_name = Label(Products_frame,text=p_weight,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=200)
            pet_name1 = Label(Products_frame,text="Price:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=230)
            pet_name = Label(Products_frame,text="Rs."+str(p_price),font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=260)
            mycursor.execute("SELECT UContact,City FROM Users WHERE UID = %s",(current_pet[2],))
            user_info = mycursor.fetchone()
            pet_name1 = Label(Products_frame,text="Location:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=290)
            pet_name = Label(Products_frame,text=user_info[1],font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=320)
            pet_name1 = Label(Products_frame,text="Want to buy!!!\nContact with the seller",font="times 22 bold",fg="White",bg="Green",bd=2)
            pet_name1.place(x=730,y=230)
            pet_name = Label(Products_frame,text="Phone No:"+ str(user_info[0]),font="times 16 bold",fg="Black",bd=2)
            pet_name.place(x=730,y=310)
            next_button = Button(Products_frame,text="Next",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:next_pet(count,pets)).place(x=730,y=500)
            prev_button = Button(Products_frame,text="Previous",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:prev_pet(count,pets)).place(x=430,y=500)
            root.mainloop()
        next_button = Button(Products_frame,text="Next",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:next_pet(count,pets)).place(x=730,y=500)
        prev_button = Button(Products_frame,text="Previous",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:prev_pet(count,pets)).place(x=430,y=500)
        root.mainloop()
    def button3():
        HideAllFrames()
        
        bird_label=Label(Products_frame,text="Dogs",font="times 22 bold italic underline",fg="red").grid(row=0,column=0,padx=20)
        mycursor.execute("SELECT * FROM Product WHERE CId = %s",(2,))
        pets = mycursor.fetchall()
        count = 0
        count = count%len(pets)
        current_pet = pets[count]
        p_name = current_pet[3]
        p_image = current_pet[4]
        p_desc = current_pet[5]
        p_weight = current_pet[6]
        p_price = current_pet[7]
        pet_frame=LabelFrame(Products_frame,bd=2,relief="groove")
        pet_frame.place(x=5,y=35,width=410,height=540)
        pet_image =ImageTk.PhotoImage(Image.open(p_image))
        Label(pet_frame,image=pet_image,bd=2).grid(row=0,column=0)
        pet_name1 = Label(Products_frame,text="Name:",font="times 16 bold",fg="Blue",bd=2)
        pet_name1.place(x=450,y=50)
        pet_name = Label(Products_frame,text=p_name,font="times 16",fg="Orange",bd=2)
        pet_name.place(x=550,y=80)
        pet_name1 = Label(Products_frame,text="Color:",font="times 16 bold",fg="Blue",bd=2)
        pet_name1.place(x=450,y=110)
        pet_name = Label(Products_frame,text=p_desc,font="times 16",fg="Orange",bd=2)
        pet_name.place(x=550,y=140)
        pet_name1 = Label(Products_frame,text="Weight:",font="times 16 bold",fg="Blue",bd=2)
        pet_name1.place(x=450,y=170)
        pet_name = Label(Products_frame,text=p_weight,font="times 16",fg="Orange",bd=2)
        pet_name.place(x=550,y=200)
        pet_name1 = Label(Products_frame,text="Price:",font="times 16 bold",fg="Blue",bd=2)
        pet_name1.place(x=450,y=230)
        pet_name = Label(Products_frame,text="Rs."+str(p_price),font="times 16",fg="Orange",bd=2)
        pet_name.place(x=550,y=260)
        mycursor.execute("SELECT UContact,City FROM Users WHERE UID = %s",(current_pet[2],))
        user_info = mycursor.fetchone()
        pet_name1 = Label(Products_frame,text="Location:",font="times 16 bold",fg="Blue",bd=2)
        pet_name1.place(x=450,y=290)
        pet_name = Label(Products_frame,text=user_info[1],font="times 16",fg="Orange",bd=2)
        pet_name.place(x=550,y=320)
        pet_name1 = Label(Products_frame,text="Want to buy!!!\nContact with the seller",font="times 22 bold",fg="White",bg="Green",bd=2)
        pet_name1.place(x=730,y=230)
        pet_name = Label(Products_frame,text="Phone No:"+ str(user_info[0]),font="times 16 bold",fg="Black",bd=2)
        pet_name.place(x=730,y=310)
        def next_pet(count,pets):
            HideAllFrames()
            count += 1
            count = count%len(pets)
            current_pet = pets[count]
            p_name = current_pet[3]
            p_image = current_pet[4]
            p_desc = current_pet[5]
            p_weight = current_pet[6]
            p_price = current_pet[7]
            bird_label=Label(Products_frame,text="Dogs",font="times 22 bold italic underline",fg="red").grid(row=0,column=0,padx=20)
            pet_frame=LabelFrame(Products_frame,bd=2,relief="groove")
            pet_frame.place(x=5,y=35,width=410,height=540)
            pet_image =ImageTk.PhotoImage(Image.open(p_image))
            Label(pet_frame,image=pet_image,bd=2).grid(row=0,column=0)
            pet_name1 = Label(Products_frame,text="Name:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=50)
            pet_name = Label(Products_frame,text=p_name,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=80)
            pet_name1 = Label(Products_frame,text="Color:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=110)
            pet_name = Label(Products_frame,text=p_desc,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=140)
            pet_name1 = Label(Products_frame,text="Weight:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=170)
            pet_name = Label(Products_frame,text=p_weight,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=200)
            pet_name1 = Label(Products_frame,text="Price:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=230)
            pet_name = Label(Products_frame,text="Rs."+str(p_price),font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=260)
            mycursor.execute("SELECT UContact,City FROM Users WHERE UID = %s",(current_pet[2],))
            user_info = mycursor.fetchone()
            pet_name1 = Label(Products_frame,text="Location:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=290)
            pet_name = Label(Products_frame,text=user_info[1],font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=320)
            pet_name1 = Label(Products_frame,text="Want to buy!!!\nContact with the seller",font="times 22 bold",fg="White",bg="Green",bd=2)
            pet_name1.place(x=730,y=230)
            pet_name = Label(Products_frame,text="Phone No:"+ str(user_info[0]),font="times 16 bold",fg="Black",bd=2)
            pet_name.place(x=730,y=310)
            next_button = Button(Products_frame,text="Next",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:next_pet(count,pets)).place(x=730,y=500)
            prev_button = Button(Products_frame,text="Previous",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:prev_pet(count,pets)).place(x=430,y=500)
            root.mainloop()
        def prev_pet(count,pets):
            HideAllFrames()
            count -= 1
            count = count%len(pets)
            current_pet = pets[count]
            p_name = current_pet[3]
            p_image = current_pet[4]
            p_desc = current_pet[5]
            p_weight = current_pet[6]
            p_price = current_pet[7]
            bird_label=Label(Products_frame,text="Dogs",font="times 22 bold italic underline",fg="red").grid(row=0,column=0,padx=20)
            pet_frame=LabelFrame(Products_frame,bd=2,relief="groove")
            pet_frame.place(x=5,y=35,width=410,height=540)
            pet_image =ImageTk.PhotoImage(Image.open(p_image))
            Label(pet_frame,image=pet_image,bd=2).grid(row=0,column=0)
            pet_name1 = Label(Products_frame,text="Name:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=50)
            pet_name = Label(Products_frame,text=p_name,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=80)
            pet_name1 = Label(Products_frame,text="Color:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=110)
            pet_name = Label(Products_frame,text=p_desc,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=140)
            pet_name1 = Label(Products_frame,text="Weight:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=170)
            pet_name = Label(Products_frame,text=p_weight,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=200)
            pet_name1 = Label(Products_frame,text="Price:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=230)
            pet_name = Label(Products_frame,text="Rs."+str(p_price),font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=260)
            mycursor.execute("SELECT UContact,City FROM Users WHERE UID = %s",(current_pet[2],))
            user_info = mycursor.fetchone()
            pet_name1 = Label(Products_frame,text="Location:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=290)
            pet_name = Label(Products_frame,text=user_info[1],font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=320)
            pet_name1 = Label(Products_frame,text="Want to buy!!!\nContact with the seller",font="times 22 bold",fg="White",bg="Green",bd=2)
            pet_name1.place(x=730,y=230)
            pet_name = Label(Products_frame,text="Phone No:"+ str(user_info[0]),font="times 16 bold",fg="Black",bd=2)
            pet_name.place(x=730,y=310)
            next_button = Button(Products_frame,text="Next",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:next_pet(count,pets)).place(x=730,y=500)
            prev_button = Button(Products_frame,text="Previous",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:prev_pet(count,pets)).place(x=430,y=500)
            root.mainloop()
        next_button = Button(Products_frame,text="Next",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:next_pet(count,pets)).place(x=730,y=500)
        prev_button = Button(Products_frame,text="Previous",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:prev_pet(count,pets)).place(x=430,y=500)
        root.mainloop()
    def button4():
        HideAllFrames()
        def get_path(path):
            file_selected = filedialog.askopenfilename(filetypes = (("Image files", "*.gif;*.png;*.jpg;*.jpeg"),("All files", "*.*") ))
            path.set(file_selected)
        def add_pet(c,u,n,i,d,w,p):
            mycursor.execute("INSERT INTO Product(CId, Uid,PName, image, PDescription, weight, Price) VALUE (%s,%s,%s,%s,%s,%s,%s)",(c,u,n,i,d,w,p))
            mydb.commit()
            button4()
        mycursor.execute("SELECT Uid from users u, registration r where u.rid=r.rid and r.username=%s",(name.get(),))
        user_id = mycursor.fetchone()[0]
        print(user_id)
        p_cid = StringVar()
        p_name = StringVar()
        p_image = StringVar()
        p_desc = StringVar()
        p_weight = StringVar()
        p_price = StringVar()
        bird_label=Label(Products_frame,text="Add New Pet",font="times 22 bold italic underline",fg="red").grid(row=0,column=0,padx=50,pady=20)
        Label(Products_frame,text="Enter number for Pet category:( 1 for Cats.  2 for Dogs.  3 for Birds)",font="times 16 bold",fg="Black",bd=2).grid(row=1,column=0)
        Entry(Products_frame,textvariable=p_cid).grid(row=1,column=1,padx=10)
        Label(Products_frame,text="Enter Pet Name:",font="times 16 bold",fg="Black",bd=2).grid(row=2,column=0)
        Entry(Products_frame,textvariable=p_name).grid(row=2,column=1,padx=10)
        Label(Products_frame,text="Enter Pet Description:",font="times 16 bold",fg="Black",bd=2).grid(row=3,column=0)
        Entry(Products_frame,textvariable=p_desc).grid(row=3,column=1,padx=10)
        Label(Products_frame,text="Enter Pet Weight:",font="times 16 bold",fg="Black",bd=2).grid(row=4,column=0)
        Entry(Products_frame,textvariable=p_weight).grid(row=4,column=1,padx=10)
        Label(Products_frame,text="Enter Pet Price:",font="times 16 bold",fg="Black",bd=2).grid(row=5,column=0)
        Entry(Products_frame,textvariable=p_price).grid(row=5,column=1,padx=10)
        Label(Products_frame,text="Enter Pet Image Location:",font="times 16 bold",fg="Black",bd=2).grid(row=6,column=0)
        Entry(Products_frame,textvariable=p_image,width=30).grid(row=6,column=1,padx=10)
        Button(Products_frame,text="Browse",font="times 12 bold",fg="black",command = lambda:get_path(p_image)).grid(row=6,column=3)
        Button(Products_frame,text="Submit",font="times 16 bold",width=17,bd=6,bg="Blue",fg="white",activebackground="light blue",command = lambda:add_pet(p_cid.get(),user_id,p_name.get(),p_image.get(),p_desc.get(),p_weight.get(),p_price.get())).grid(row=7,column=0,padx=100)
    def del_pet(pet_id):
        mycursor.execute("DELETE FROM Product WHERE pid=%s",(pet_id,))
        mydb.commit()
        button5()
    def button5():
        HideAllFrames()
        Label(Products_frame,text="Delete Pet",font="times 22 bold italic underline",fg="red").grid(row=0,column=0,padx=20)
        mycursor.execute("SELECT city from users u, registration r where u.rid=r.rid and r.username=%s",(name.get(),))
        city = mycursor.fetchone()
        mycursor.execute("SELECT * FROM Product p, users u  WHERE p.uid=u.uid and u.city = %s",(city[0],))
        pets = mycursor.fetchall()
        if len(pets)==0:
            Label(Products_frame,text="Sorry no pet to show.",font="arial 20 bold italic",bg="light yellow",fg="Dark Red").grid(row=1,column=0,padx=250)
            root.mainloop()
        count = 0
        current_pet = pets[count]
        p_name = current_pet[3]
        p_image = current_pet[4]
        p_desc = current_pet[5]
        p_weight = current_pet[6]
        p_price = current_pet[7]
        pet_frame=LabelFrame(Products_frame,bd=2,relief="groove")
        pet_frame.place(x=5,y=35,width=410,height=540)
        pet_image =ImageTk.PhotoImage(Image.open(p_image))
        Label(pet_frame,image=pet_image,bd=2).grid(row=0,column=0)
        pet_name1 = Label(Products_frame,text="Name:",font="times 16 bold",fg="Blue",bd=2)
        pet_name1.place(x=450,y=50)
        pet_name = Label(Products_frame,text=p_name,font="times 16",fg="Orange",bd=2)
        pet_name.place(x=550,y=80)
        pet_name1 = Label(Products_frame,text="Color:",font="times 16 bold",fg="Blue",bd=2)
        pet_name1.place(x=450,y=110)
        pet_name = Label(Products_frame,text=p_desc,font="times 16",fg="Orange",bd=2)
        pet_name.place(x=550,y=140)
        pet_name1 = Label(Products_frame,text="Weight:",font="times 16 bold",fg="Blue",bd=2)
        pet_name1.place(x=450,y=170)
        pet_name = Label(Products_frame,text=p_weight,font="times 16",fg="Orange",bd=2)
        pet_name.place(x=550,y=200)
        pet_name1 = Label(Products_frame,text="Price:",font="times 16 bold",fg="Blue",bd=2)
        pet_name1.place(x=450,y=230)
        pet_name = Label(Products_frame,text="Rs."+str(p_price),font="times 16",fg="Orange",bd=2)
        pet_name.place(x=550,y=260)
        mycursor.execute("SELECT UContact,City FROM Users WHERE UID = %s",(current_pet[2],))
        user_info = mycursor.fetchone()
        pet_name1 = Label(Products_frame,text="Location:",font="times 16 bold",fg="Blue",bd=2)
        pet_name1.place(x=450,y=290)
        pet_name = Label(Products_frame,text=user_info[1],font="times 16",fg="Orange",bd=2)
        pet_name.place(x=550,y=320)
        
        
        def next_pet(count,pets):
            HideAllFrames()
            count += 1
            count = count%len(pets)
            current_pet = pets[count]
            p_name = current_pet[3]
            p_image = current_pet[4]
            p_desc = current_pet[5]
            p_weight = current_pet[6]
            p_price = current_pet[7]
            Label(Products_frame,text="Pets Near You",font="times 22 bold italic underline",fg="red").grid(row=0,column=0,padx=20)
            pet_frame=LabelFrame(Products_frame,bd=2,relief="groove")
            pet_frame.place(x=5,y=35,width=410,height=540)
            pet_image =ImageTk.PhotoImage(Image.open(p_image))
            Label(pet_frame,image=pet_image,bd=2).grid(row=0,column=0)
            pet_name1 = Label(Products_frame,text="Name:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=50)
            pet_name = Label(Products_frame,text=p_name,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=80)
            pet_name1 = Label(Products_frame,text="Color:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=110)
            pet_name = Label(Products_frame,text=p_desc,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=140)
            pet_name1 = Label(Products_frame,text="Weight:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=170)
            pet_name = Label(Products_frame,text=p_weight,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=200)
            pet_name1 = Label(Products_frame,text="Price:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=230)
            pet_name = Label(Products_frame,text="Rs."+str(p_price),font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=260)
            mycursor.execute("SELECT UContact,City FROM Users WHERE UID = %s",(current_pet[2],))
            user_info = mycursor.fetchone()
            pet_name1 = Label(Products_frame,text="Location:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=290)
            pet_name = Label(Products_frame,text=user_info[1],font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=320)
            Button(Products_frame,text="Delete This Pet",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:del_pet(current_pet[0])).place(x=730,y=230)
            next_button = Button(Products_frame,text="Next",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:next_pet(count,pets)).place(x=730,y=500)
            prev_button = Button(Products_frame,text="Previous",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:prev_pet(count,pets)).place(x=430,y=500)
            root.mainloop()
        def prev_pet(count,pets):
            HideAllFrames()
            count -= 1
            count = count%len(pets)
            current_pet = pets[count]
            p_name = current_pet[3]
            p_image = current_pet[4]
            p_desc = current_pet[5]
            p_weight = current_pet[6]
            p_price = current_pet[7]
            Label(Products_frame,text="Pets Near You",font="times 22 bold italic underline",fg="red").grid(row=0,column=0,padx=20)
            pet_frame=LabelFrame(Products_frame,bd=2,relief="groove")
            pet_frame.place(x=5,y=35,width=410,height=540)
            pet_image =ImageTk.PhotoImage(Image.open(p_image))
            Label(pet_frame,image=pet_image,bd=2).grid(row=0,column=0)
            pet_name1 = Label(Products_frame,text="Name:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=50)
            pet_name = Label(Products_frame,text=p_name,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=80)
            pet_name1 = Label(Products_frame,text="Color:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=110)
            pet_name = Label(Products_frame,text=p_desc,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=140)
            pet_name1 = Label(Products_frame,text="Weight:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=170)
            pet_name = Label(Products_frame,text=p_weight,font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=200)
            pet_name1 = Label(Products_frame,text="Price:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=230)
            pet_name = Label(Products_frame,text="Rs."+str(p_price),font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=260)
            mycursor.execute("SELECT UContact,City FROM Users WHERE UID = %s",(current_pet[2],))
            user_info = mycursor.fetchone()
            pet_name1 = Label(Products_frame,text="Location:",font="times 16 bold",fg="Blue",bd=2)
            pet_name1.place(x=450,y=290)
            pet_name = Label(Products_frame,text=user_info[1],font="times 16",fg="Orange",bd=2)
            pet_name.place(x=550,y=320)
            Button(Products_frame,text="Delete This Pet",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:del_pet(current_pet[0])).place(x=730,y=230)
            next_button = Button(Products_frame,text="Next",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:next_pet(count,pets)).place(x=730,y=500)
            prev_button = Button(Products_frame,text="Previous",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:prev_pet(count,pets)).place(x=430,y=500)
            root.mainloop()
        Button(Products_frame,text="Delete This Pet",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:del_pet(current_pet[0])).place(x=730,y=230)
        next_button = Button(Products_frame,text="Next",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:next_pet(count,pets)).place(x=730,y=500)
        prev_button = Button(Products_frame,text="Previous",font="times 20 bold",width=17,bd=6,bg="White",fg="Green",activebackground="Yellow",command= lambda:prev_pet(count,pets)).place(x=430,y=500)
        root.mainloop()  
    Button(Button_frame,text="Home",font="times 14 bold",width=22,bd=6,bg="Gold",fg="white",activebackground="light blue",command=near_you).grid(row=0,column=0,padx=10,pady=5)  
    bird_button=Button(Button_frame,text="Birds",font="times 14 bold",width=22,bd=6,bg="Gold",fg="white",activebackground="light blue",command = button1)
    bird_button.grid(row=1,column=0,padx=10,pady=5)
    cat_button=Button(Button_frame,text="Cats",font="times 14 bold",width=22,bd=6,bg="Gold",fg="white",activebackground="light blue",command = button2)
    cat_button.grid(row=2,column=0,padx=10,pady=5)
    dog_button=Button(Button_frame,text="Dogs",font="times 14 bold",width=22,bd=6,bg="Gold",fg="white",activebackground="light blue",command = button3)
    dog_button.grid(row=3,column=0,padx=10,pady=5)
    add_button =Button(Button_frame,text="Add Pet",font="times 14 bold",width=22,bd=6,bg="Gold",fg="white",activebackground="light blue",command = button4)
    add_button.grid(row=4,column=0,padx=10,pady=5)
    del_button =Button(Button_frame,text="Delete Pet",font="times 14 bold",width=22,bd=6,bg="Gold",fg="white",activebackground="light blue",command = button5)
    del_button.grid(row=5,column=0,padx=10,pady=5)
    image_animals = ImageTk.PhotoImage(Image.open("D:\ProjectDB\pet2.png"))
    Animal_frame=LabelFrame(root,bd=2,bg='Light green')
    Animal_frame.place(x=2,y=450,width=300,height=230)
    animal_1=Label(Animal_frame,image=image_animals,bg='Light green')
    animal_1.grid(row=0,column=0,padx=30,pady=17)
    near_you()
    root.mainloop()
main_gui()